version: 2
updates:
  - package-ecosystem: "npm" # Change to "pip", "maven", "gradle", etc., as needed.
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "production" # Only update production dependencies

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
