name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated from v2/v3 to v4

    - name: Setup Node.js
      uses: actions/setup-node@v4  # Updated from v2/v3 to v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Upload test results (if needed)
      uses: actions/upload-artifact@v4  # Updated from v3 to v4
      if: always()
      with:
        name: test-results
        path: |
          test-results/
          coverage/
