# File: .github/workflows/deploy.yml
name: Deploy to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or PR to the main branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job to build the site
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Set your project's Node.js version
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build # This must be the script in your package.json that builds your site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist # Change this to your build output folder (e.g., './build', './out')

  # Job to deploy the site - THIS WILL WAIT FOR APPROVAL
  deploy:
    environment: # This links to the environment you created
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build # This job depends on the build job finishing successfully

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
